version: '3'

services:
  
  mongo:
    build:
      context: ./database

    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - "27017:27017"
      - "28017:28017"

  monitoring:
    build: 
      context: ./MonitoringService

    depends_on:
      - mongo
    environment:
      - NODE_SERVER_PORT=3001
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=trivago_audit
      - BUSINESS_KEY=businesskey
    volumes:
      - ./MonitoringService:/usr/src/app

  business:
    build: 
      context: ./BusinessLogic

    depends_on:
      - mongo
      - monitoring
    environment:
      - NODE_SERVER_PORT=3000
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=trivago_dev
      - TESTING_DB_NAME=trivago_test
      - MONITOR_URI=http://monitoring:3001
      - API_GATEWAY_KEY=apigateway
      - BUSINESS_KEY=businesskey
      - PUBLIC_ACCESS_KEY=public-api-secret
      - PRIVATE_ACCESS_KEY=private-api-secret
    volumes:
      - ./BusinessLogic:/usr/src/app

  gateway:
    build: 
      context: ./ApiGateWay

    depends_on:
      - mongo
      - business
    environment:
      - API_GW_PORT=8080
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=trivago_gw
      - TESTING_DB_NAME=trivago_gw_test
      - BUSINESS_SERVICE_URL=http://business:3000
      - API_GATEWAY_KEY=apigateway 
    ports:
      - "8080:8080"
    volumes:
      - ./ApiGateWay:/usr/src/app


volumes:
  mongodata:
    driver: local
  mongoconfig:
    driver: local

