# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  ApiGWJob:
    docker:
      # specify the version you desire here
      - image: circleci/node:12
      - image: circleci/mongo:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd ApiGateWay
      - run: npm install
      - run: npm run test-cov

  BusinessServiceJob:
    docker:
      # specify the version you desire here
      - image: circleci/node:12
      - image: circleci/mongo:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd ApiGateWay
      - run: npm install
      - run: npm run test-cov


workflows:
  version: 2
  one_and_two:
    jobs:
      - ApiGWJob
      - BusinessServiceJob
